org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.cache.cleanup=false
group=fi.dy.masa
mod_id=environmentalcreepers
mod_name=Environmental Creepers
author=masa
mod_file_name=environmentalcreepers-fabric
# Current mod version
mod_version=1.6.1
# Minecraft, Fabric and mappings versions
minecraft_version_out=1.21.4
minecraft_version=1.21.4
mappings_version=1.21.4+build.8
fabric_loader_version=0.16.10
mod_menu_version=13.0.2
